### PR TITLE
Add jwt authentication

### PR DESCRIPTION
**Pull request by kaesrel**
I have added the **jwt** authentication and the models are updated.

The models have to somehow be migrated, but migrating in flask is tricky.
I need help with deployment.

Just need two people to approve this, and then we can merge this branch to master.

### Register User:
**POST** method
```
https://wcg-apis-test.herokuapp.com/register_user?username=<your_username>&password=<your_password>
```

### Login:
**POST** method (maybe I should allow GET too)
```
https://wcg-apis-test.herokuapp.com/login
```
Use the postman to invoke the method with authentication (see screenshot).
image

A bearer token will be returned.
image

### Token Usage Example
**POST** method
```
https://wcg-apis-test.herokuapp.com/registration?citizen_id=<citizen_id>&name=<name>&surname=<surname>&birth_date=<birth_date>&occupation=<occupation>&address=<address>&phone_number=<phone_number>&is_risk=<true_or_false>
```
image

### Caveats:
Right now, you cannot reset the database via API usage unless there is a way to manually set permissions.

### CODE REVIEW

**Comment by kaesrel** [comment]
I got this after I tried to login:

**Comment by kaesrel** [comment]
I temporarily fixed it by adding a dummy SECRET KEY.
Still need to externalize SECRET KEY.

**Review by ZEZAY — APPROVED** [review]
I checked!

**Comment by kaesrel** [comment]
Externalization successful.

**Comment by Sahadporn** [comment]
Everything seems to work. Approved.

**Review by Sahadporn — APPROVED** [review]

**Pull request merged**
